SDL2_INC_DIR = C:\SDL2_dev\mingw\i686-w64-mingw32\include\SDL2
SDL2_LIB_DIR = C:\SDL2_dev\mingw\i686-w64-mingw32\lib

CXX = gcc

INCLUDE_PATHS = -I$(SDL2_INC_DIR)

LIBRARY_PATHS = -L$(SDL2_LIB_DIR)

COMPILER_FLAGS = -Wall
RELEASE_COMPILER_FLAGS = -mwindows

LINKER_FLAGS = -lmingw32 -lSDL2main -lSDL2 -lSDL2_ttf

OBJS = bezier.c
OBJ_NAME = output

all: $(OBJS)
	$(CXX) $(OBJS) $(INCLUDE_PATHS) $(LIBRARY_PATHS) $(COMPILER_FLAGS) $(LINKER_FLAGS) -o $(OBJ_NAME)

release: $(OBJS)
	$(CXX) $(OBJS) $(INCLUDE_PATHS) $(LIBRARY_PATHS) $(RELEASE_COMPILER_FLAGS) $(LINKER_FLAGS) -o $(OBJ_NAME)
